"""The register C15 clause 3 compares against, and the reason it had nothing to compare.

Clause 3 catches the vendoring case the other two miss entirely: a copied measure
implementation under a new name declares no dependency and imports nothing denied. It works
by comparing normalized content hashes against hashes of the oracle's own source files.

**It has never run.** `denied_source_hashes` was supplied in two test cases and by nothing
else, so every real invocation of C15 reported `PASSED — 2 of 3 clauses (no denied source
hashes supplied)`. The module's own comment names the shape: a report that reads green over a
check that did not run. This loader is what ends that.

**Where the hashes come from, and why not from here.** They are produced inside the oracle
image by `harness/oracle/fingerprints.py` and written to `policy/oracle-source-hashes.json`.
They cannot be produced out here: D54 says the oracle's outputs cross the boundary as data and
its code never crosses at all, so hashing outside would mean extracting CriMe's source text
into this repository, which is precisely what D54 forbids. Only digests leave.

**Fail closed, and distinguish the two ways of being empty.** An absent register and an
unreadable one raise; they are not an empty mapping. An empty mapping still disables clause 3
rather than satisfying it, which is C15's existing behaviour and is left alone — but a
register that exists and parses to zero entries is a build that produced nothing, and this
loader refuses it rather than handing C15 a silent two-clause pass.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

__all__ = ["DEFAULT_PATH", "SourceHashes", "SourceHashesUnavailable", "load"]

DEFAULT_PATH: Final = Path(__file__).resolve().parents[2] / "policy" / "oracle-source-hashes.json"


class SourceHashesUnavailable(RuntimeError):
    """The register could not be read. C15 must not fall back to two clauses silently."""


@dataclass(frozen=True)
class SourceHashes:
    """`{normalized digest: the oracle source file it came from}`, plus its provenance."""

    version: int
    oracle_commit_sha: str
    hashes: dict[str, str]

    def as_mapping(self) -> dict[str, str]:
        return dict(self.hashes)


def load(path: Path = DEFAULT_PATH) -> SourceHashes:
    if not path.is_file():
        raise SourceHashesUnavailable(
            f"{path} does not exist. It is generated by running harness/oracle/fingerprints.py "
            "inside the pinned oracle image; C15 clause 3 cannot run without it."
        )
    try:
        document: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SourceHashesUnavailable(f"{path} does not parse: {exc}") from exc

    raw = document.get("hashes")
    if not isinstance(raw, dict) or not raw:
        # D57 at the loader rather than at the caller. A register that parsed to nothing is a
        # generation failure, and handing it on as an empty mapping would turn that failure
        # into C15 reporting two of three clauses clean.
        raise SourceHashesUnavailable(
            f"{path} carries no hashes; a register of nothing is not a register"
        )
    hashes: dict[str, str] = {str(key): str(value) for key, value in raw.items()}  # pyright: ignore[reportUnknownVariableType, reportUnknownArgumentType]

    sha = str(document.get("oracle_commit_sha", ""))
    if not sha.strip():
        # The pin is what makes a digest re-derivable. Without it the register records
        # hashes of some version of the oracle and nobody can say which.
        raise SourceHashesUnavailable(
            f"{path} names no oracle commit; its hashes are unattributable"
        )

    return SourceHashes(
        version=int(document.get("version", 0)),
        oracle_commit_sha=sha,
        hashes=hashes,
    )
