"""Doc lint — the CI gate the Documentation Standard commits to.

Checks the header contract, never the prose. Nothing here can verify that a
document is true; it verifies that the document has declared what would show it
false, and to whom it answers.

Also regenerates docs/README.md, the register index, from the frontmatter it
finds — an index maintained by hand is a drift generator.

    python3 scripts/lint_docs.py [--check]     # --check fails if README is stale
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent / "docs"
INDEX = DOCS / "README.md"

REQUIRED = ("status", "owner", "enforcement", "evidence", "review_after")
OPTIONAL = ("falsifies_if", "supersedes")

VALID_STATUS = {"frozen", "provisional", "directional"}
VALID_OWNER = {"human", "generated", "executable"}
VALID_ENFORCEMENT = {"ci-gate", "schema", "generated", "review-cadence", "none"}

TIER_NAMES = {
    0: "Constitution",
    1: "Architecture",
    2: "Build protocol",
    3: "Agent specifications",
    4: "Security and governance",
    5: "Product",
    6: "Operations",
    7: "Meta",
}


def parse_frontmatter(path: Path) -> tuple[dict[str, str], list[str]]:
    """Minimal frontmatter parser. Deliberately not YAML: a dependency here would
    make the lint that guards the register depend on the supply chain the register
    is supposed to govern."""
    text = path.read_text()
    errors: list[str] = []
    if not text.startswith("---\n"):
        return {}, [f"{path.name}: missing frontmatter"]

    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, [f"{path.name}: unterminated frontmatter"]

    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            errors.append(f"{path.name}: unparseable frontmatter line: {line.strip()[:60]}")
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields, errors


def check(path: Path) -> list[str]:
    fields, errors = parse_frontmatter(path)
    if not fields:
        return errors

    rel = path.relative_to(DOCS.parent)

    for key in REQUIRED:
        if not fields.get(key):
            errors.append(f"{rel}: missing or empty required field '{key}'")

    for key in fields:
        if key not in REQUIRED + OPTIONAL:
            errors.append(f"{rel}: unknown frontmatter key '{key}'")

    status = fields.get("status", "")
    if status and status not in VALID_STATUS:
        errors.append(f"{rel}: status '{status}' not in {sorted(VALID_STATUS)}")

    owner = fields.get("owner", "")
    if owner and owner not in VALID_OWNER:
        errors.append(f"{rel}: owner '{owner}' not in {sorted(VALID_OWNER)}")

    enforcement = fields.get("enforcement", "")
    if enforcement and enforcement not in VALID_ENFORCEMENT:
        errors.append(f"{rel}: enforcement '{enforcement}' not in {sorted(VALID_ENFORCEMENT)}")

    # The rule that makes an early register a set of predictions rather than
    # speculation: no evidence means you must say what would prove it wrong.
    evidence = fields.get("evidence", "")
    if evidence.lower().startswith("none") and not fields.get("falsifies_if"):
        errors.append(f"{rel}: evidence is 'none' but falsifies_if is absent")

    if owner == "generated" and enforcement != "generated":
        errors.append(f"{rel}: owner 'generated' requires enforcement 'generated'")

    return errors


def is_stub(path: Path) -> bool:
    return "**Status: stub.**" in path.read_text()


def build_index(entries: list[tuple[Path, dict[str, str]]]) -> str:
    lines = [
        "# Alfred documentation register",
        "",
        "**Generated by `scripts/lint_docs.py`. Do not edit by hand.**",
        "",
        "Documents are classified by what stops them from lying, never by topic. See",
        "[Documentation Standard](tier7/documentation-standard.md) for the header contract,",
        "the stub policy, and the authorship boundary.",
        "",
    ]

    total = len(entries)
    # A document is a stub because its body says so, not because its evidence
    # field is honest about being empty. Tier 0 documents are fully written and
    # legitimately declare `evidence: none` — conflating the two mislabels
    # exactly the documents that were most careful.
    stubs = sum(1 for p, _ in entries if is_stub(p))
    executable = sum(1 for _, f in entries if f.get("owner") in {"executable", "generated"})
    lines += [
        f"**{total} documents** · {total - stubs} written, {stubs} stubs · "
        f"{executable} executable or generated ({executable * 100 // total}%)",
        "",
    ]

    by_tier: dict[int, list[tuple[Path, dict[str, str]]]] = {}
    for path, fields in entries:
        tier = int(path.parent.name.removeprefix("tier"))
        by_tier.setdefault(tier, []).append((path, fields))

    for tier in sorted(by_tier):
        lines += [
            f"## Tier {tier} — {TIER_NAMES.get(tier, '')}",
            "",
            "| Document | Status | Owner | Enforcement | Written |",
            "|---|---|---|---|---|",
        ]
        for path, fields in sorted(by_tier[tier], key=lambda e: e[0].name):
            title = next(
                (l[2:].strip() for l in path.read_text().splitlines() if l.startswith("# ")),
                path.stem,
            )
            written = "stub" if is_stub(path) else "full"
            rel = f"tier{tier}/{path.name}"
            lines.append(
                f"| [{title}]({rel}) | {fields.get('status','')} | {fields.get('owner','')} "
                f"| `{fields.get('enforcement','')}` | {written} |"
            )
        lines.append("")

    return "\n".join(lines)


def stub_register() -> tuple[set[str], set[str]]:
    """`gen_doc_stubs.py`'s register and its declared not-generated set, read by AST.

    Read rather than imported: the lint that guards the register must not execute the
    generator to learn what is in it, for the same reason the frontmatter parser above is
    hand-written rather than a YAML dependency.
    """
    source = Path(__file__).resolve().parent / "gen_doc_stubs.py"
    tree = ast.parse(source.read_text())

    registered = {
        f"tier{ast.literal_eval(node.args[0])}/{ast.literal_eval(node.args[1])}"
        for node in ast.walk(tree)
        if isinstance(node, ast.Call) and getattr(node.func, "id", "") == "Doc" and len(node.args) >= 2
    }

    not_generated: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign) or getattr(node.target, "id", "") != "NOT_GENERATED":
            continue
        value = node.value
        # `frozenset({...})` is a call, which literal_eval refuses. Unwrap to the set literal
        # inside it rather than loosening the evaluation.
        if isinstance(value, ast.Call) and getattr(value.func, "id", "") == "frozenset" and value.args:
            value = value.args[0]
        not_generated = set(ast.literal_eval(value)) if value is not None else set()

    return registered, not_generated


def check_register(paths: list[Path]) -> list[str]:
    """Every document on disk is either in the register or declared not-generated, and back.

    The drift this catches is silent and one-directional: a document added without a register
    entry changes nothing observable, so the register sat at 55 entries against 63 documents
    with nothing reporting it. The reverse direction matters too -- an entry naming a document
    that was deleted or renamed makes the generator create it again on the next run.
    """
    registered, not_generated = stub_register()
    if not registered:
        # Fail closed. An AST walk that found no Doc calls has stopped working, and reporting
        # "every document is accounted for" would be the exact vacuity this check is for.
        return ["gen_doc_stubs.py register parsed to zero entries — the reader is broken"]

    on_disk = {f"{path.parent.name}/{path.stem}" for path in paths}
    accounted = registered | not_generated

    errors = [
        f"{slug}.md is on disk and is in neither gen_doc_stubs.py's REGISTER nor its NOT_GENERATED"
        for slug in sorted(on_disk - accounted)
    ]
    errors += [
        f"gen_doc_stubs.py names {slug} which is not on disk"
        for slug in sorted(accounted - on_disk)
    ]
    overlap = registered & not_generated
    errors += [f"gen_doc_stubs.py lists {slug} in both REGISTER and NOT_GENERATED" for slug in sorted(overlap)]
    return errors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the index is stale")
    args = parser.parse_args()

    # Generated navigation carries no frontmatter: it is derived from the register
    # rather than being part of it. Working-folder contracts (ICM invariant 4) are
    # not register documents — `CONTEXT.md` in any tier or in `docs/` itself is a
    # task contract, not a tier document, and must not be checked against the header
    # contract or the stub register.
    generated = {INDEX, DOCS / "READING-MAP.md"}
    paths = sorted(p for p in DOCS.rglob("*.md") if p not in generated and p.name != "CONTEXT.md")
    if not paths:
        print("no documents found", file=sys.stderr)
        raise SystemExit(1)

    all_errors: list[str] = []
    entries: list[tuple[Path, dict[str, str]]] = []
    for path in paths:
        errors = check(path)
        all_errors.extend(errors)
        fields, _ = parse_frontmatter(path)
        if fields:
            entries.append((path, fields))

    all_errors.extend(check_register(paths))

    index = build_index(entries)
    if args.check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != index:
            all_errors.append("docs/README.md is stale — run scripts/lint_docs.py")
    else:
        INDEX.write_text(index)

    if all_errors:
        for error in all_errors:
            print(f"FAIL {error}")
        print(f"\n{len(all_errors)} problem(s) across {len(paths)} document(s)")
        raise SystemExit(1)

    registered, not_generated = stub_register()
    print(
        f"OK {len(paths)} documents, header contract satisfied; "
        f"stub register accounts for all of them ({len(registered)} generated, "
        f"{len(not_generated)} declared not-generated)"
    )


if __name__ == "__main__":
    main()
